source $HOME/.vimprofile

"""OPTIONS"""

set backspace=indent,eol,start
syntax on
set clipboard=unnamedplus
func UpdateViminfo(timer)
    rviminfo
    wviminfo
endfunc
let timer = timer_start(1000, 'UpdateViminfo', {'repeat': -1})
set mouse=a
set autoindent
set ruler

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set textwidth=79
set colorcolumn=80

set formatoptions=rcql
set nojoinspaces

" conceal
let g:tex_conceal="adgmb"
" hi Conceal ctermfg=darkgray ctermbg=None
set conceallevel=2
set concealcursor=
hi Conceal ctermbg=None
" powerline
set laststatus=2

" searching
set incsearch
set hlsearch
set ignorecase
set smartcase
" search results in middle of page
nnoremap n nzz
nnoremap N Nzz

hi clear SpellBad
hi SpellBad cterm=underline,bold
set spellcapcheck=
set thesaurus +=/home/dustin/.vim/mthesaur.txt

set history=5000

set number

let softwrap=100
let winsize=100
set breakindent
set showbreak=\ \ 

" folding
set foldmethod=syntax
nnoremap <Space> za

" fix status line
set shortmess=a
set cmdheight=2

" highlight bad whitespace
highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd Syntax * syn match ExtraWhitespace /\s\+$\|\t\+/ containedin=ALL


"""MAPS"""

" colemak swap j/k for navigation
noremap j gk
noremap k gj
onoremap <silent> j gk
onoremap <silent> k gj
" use K,J to skip half screenfulls
noremap K <c-d>
noremap J <c-u>
" J used to 'join' lines, use M instead to 'merge' them
noremap M J

" automatically wrap paramter lists in code
let mapleader=","
map <Leader>a <Leader>r<Leader>s
map <Leader>r 0/(<Enter>a<Enter><Esc>:noh<Enter><Esc>
map <Leader>s 079l/,<Enter>Nlxi<Enter><Esc>:noh<Enter><Esc>



"""FILETYPE SPECIFICS"""

function SoftWrapText()
    set wrap
    set linebreak
    set colorcolumn=
    " autocmd VimEnter * if &diff | windo set wrap | endif
    autocmd VimResized,BufEnter,BufWritePost * if !&diff && (&columns > softwrap) | let &columns=softwrap | endif
endfunction

autocmd Bufenter stdin set nonumber
autocmd FileType tex set fo=racql | set spell
autocmd FileType mail set syntax=markdown
autocmd FileType text,mail,markdown set fo= | set spell | exe SoftWrapText()
autocmd FileType markdown set concealcursor=
autocmd FileType c,cpp set tabstop=2 | set softtabstop=2 | set shiftwidth=2
autocmd FileType gitcommit set fo-=a | set nofoldenable
autocmd Bufenter .vimprofile set ft=vim
autocmd FileType cython set commentstring=#%s
" python
let g:pyindent_open_paren = '&sw'
let g:pyindent_nested_paren = '&sw'
let g:pyindent_continue = '&sw'
" auto compile
autocmd BufWritePost *md silent !~/bin/pancomp.sh % 2>/dev/null &
com Panc execute 'silent !pancomp.sh % &' | redraw!
autocmd BufWritePost *tex silent !~/bin/tex2pdf.sh % 2>&1 1>/dev/null &
com Texc !tex2pdf.sh %
