source $HOME/.vimprofile

" General maps
noremap j k
noremap k j
" Use K,J to skip half screenfulls
noremap K <c-d>
noremap J <c-u>
" 'Merge' lines, since we can't 'join' them
noremap M J
"noremap y "+y
"noremap yy "+yy
"noremap p "+p
imap vv <Esc>
imap vV vt<Bs>vt<Bs>
cmap vv <C-c>
cmap VV <c-f>
imap <c-f> <c-g>u<Esc>[s1z=`]a<c-g>u
nmap <c-f> [s1z=<c-o>
imap <c-t> <c-g>u<Esc>]s1z=`]a<c-g>u
nmap <c-t> ]s1z=

" Advanced maps
map F :e<Enter>G
let mapleader=","
" Wrap comments
map <Leader>a <Leader>r<Leader>s
map <Leader>r 0/(<Enter>a<Enter>vv:noh<Enter>vv
map <Leader>s 079l/,<Enter>Nlxi<Enter>vv:noh<Enter>vv

" Syntax and tabstops
let fortran_free_source=1
let g:tex_conceal="adgmb"
hi Conceal NONE
set concealcursor=""
syntax on
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab

highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd Syntax * syn match ExtraWhitespace /\s\+$\|\t\+/ containedin=ALL

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase
" Search results in middle of page
nnoremap n nzz
nnoremap N Nzz

set textwidth=79
set colorcolumn=80
set formatoptions=rcql
set nojoinspaces
set ruler

set clipboard=unnamed
set mouse=a

hi clear SpellBad
hi SpellBad cterm=underline,bold
set thesaurus +=/home/dustin/.vim/mthesaur.txt

set history=5000

set number

autocmd Bufenter stdin set nonumber
autocmd FileType tex,text,mail set fo=racqlt | set spell
autocmd FileType markdown set fo=racqlt | set tabstop=4 | set shiftwidth=4
autocmd FileType c,cpp,cuda set comments-=://
autocmd FileType c,cpp,cuda set comments+=://!
autocmd FileType c,cpp,cuda set comments+=:///
autocmd FileType c,cpp,cuda set comments+=://
autocmd FileType c,cpp,cuda set commentstring=//%s
autocmd FileType c,cpp,fortran | set tabstop=4 | set shiftwidth=4
autocmd FileType gitcommit set fo-=a
autocmd Bufenter .vimprofile set ft=vim
autocmd Bufenter *.rdf set ft=config | syn match configcomment "!.*"
autocmd FileType cython set commentstring=#%s

" Python
let g:pyindent_open_paren = '&sw'
let g:pyindent_nested_paren = '&sw'
let g:pyindent_continue = '&sw'

autocmd BufWritePost *md silent !~/bin/pancomp.sh % 2>/dev/null &
autocmd BufWritePost *tex silent !~/bin/tex2pdf.sh % 2>&1 1>/dev/null &
com Panc execute 'silent !pancomp.sh % &' | redraw!
com Texc !tex2pdf.sh %

" Folding
set foldmethod=syntax
nnoremap <Space> za

" Fix status line
set shortmess=a
set cmdheight=2
