# Scheme name: Material
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming)
"attributes" = "base09"
"comment" = { fg = "base03" }
"constant" = { fg = "base09" }
"constant.character.escape" = { fg = "base0C" }
"function" = { fg = "base0D" }
"keyword" = { fg = "base0E" }
"operator" = { fg = "base05" }
"punctuation" = { fg = "base05" }
"string" = { fg = "base0B" }
# "string.regexp" = { fg = "red" }
# "tag" = { fg = "pink" }
"type" = { fg = "base0A" }
# "type.enum.variant" = { fg = "foreground", modifiers = ["italic"] }
"variable" = { fg = "base05" }
# "variable.builtin" = { fg = "base0E", modifiers = ["italic"] }
# "variable.parameter" = { fg ="base08-bright" }
# # "variable.other.member" = { fg ="base0B" }
# "variable.other.member" = { fg = "base08", modifiers = ["italic"] }

"diff.plus" = { fg = "base0B" }
"diff.delta" = { fg = "base09" }
"diff.minus" = { fg = "base08" }

"ui.background" = { fg = "base05", bg = "base00" }
"ui.bufferline" = { fg = "base04", bg = "base01" }
"ui.bufferline.active" = { fg = "base05", bg = "base02", modifiers = ["bold"] }
"ui.cursor" =  { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
# "ui.cursorline.primary" = { bg = "background_dark" }
"ui.help" = { fg = "base06", bg = "base01" }
# "ui.debug" = { fg = "red" }
# "ui.highlight.frameline" = { fg = "black", bg = "red" }
"ui.linenr" = { fg = "base03" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"]}
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { fg = "base01" }
"ui.selection" = { bg = "base02" }
# "ui.selection.primary" = { bg = "primary_highlight" }
"ui.statusline" = { fg = "base04", bg = "base01" }
# "ui.statusline.inactive" = { fg = "comment", bg = "background_dark" }
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = { fg = "base05" }
"ui.text.focus" = { fg = "base05" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base03" }
# "ui.virtual.wrap" = { fg = "subtle" }
"ui.window" = { fg = "base01" }

"error" = { fg = "base08", modifiers = ["bold"] }
"warning" = { fg = "base0A", modifiers = ["bold"] }
"hint" = { fg = "base04", modifiers = ["bold"] }
"info" = { fg = "base04", modifiers = ["bold"] }

"markup.heading" = { fg = "base0D", modifiers = ["bold"] }
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = { fg = "base0C", modifiers = ["italic"] }
"markup.raw" = { fg = "base0B" }

"diagnostic" = { underline = { color = "base09", style = "curl" } }
"diagnostic.error" = { underline = { color = "base08", style = "curl" } }

[palette]
base00 = "#263238" # Default Background
base01 = "#2e3c43" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#314549" # Selection Background
base03 = "#546e7a" # Comments, Invisibles, Line Highlighting
base04 = "#b2ccd6" # Dark Foreground (Used for status bars)
base05 = "#eeffff" # Default Foreground, Caret, Delimiters, Operators
base06 = "#eeffff" # Light Foreground (Not often used)
base07 = "#ffffff" # Light Background (Not often used)
base08 = "#f07178" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#f78c6c" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#ffcb6b" # Classes, Markup Bold, Search Text Background
base0B = "#c3e88d" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#89ddff" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#82aaff" # Functions, Methods, Attribute IDs, Headings
base0E = "#c792ea" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#ff5370" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
base10 = "#202632"
base11 = "#101622"
base08-bright = "#f27e85"
base0A-bright = "#ffd079"
base0B-bright = "#c9eb98"
base0C-bright = "#94e1ff"
base0D-bright = "#8eb2ff"
base0E-bright = "#cd9cec"