"attributes" = "base09"
"comment" = { fg = "base03" }
"constant" = { fg = "base09" }
"constant.character.escape" = { fg = "base0C" }
"function" = { fg = "base0D" }
"keyword" = { fg = "base0E" }
"operator" = { fg = "base05" }
"punctuation" = { fg = "base05" }
"string" = { fg = "base0B" }
# "string.regexp" = { fg = "red" }
# "tag" = { fg = "pink" }
"type" = { fg = "base0A" }
# "type.enum.variant" = { fg = "foreground", modifiers = ["italic"] }
"variable" = { fg = "base08" }
"variable.builtin" = { fg = "base0E", modifiers = ["italic"] }
"variable.parameter" = { fg ="base08", modifiers = ["italic"] }
"variable.other.member" = { fg ="base0B" }

"diff.plus" = { fg = "base0B" }
"diff.delta" = { fg = "base09" }
"diff.minus" = { fg = "base08" }

"ui.background" = { fg = "base05", bg = "base00" }
"ui.cursor" =  { fg = "base04", modifiers = ["dim"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["dim"] }
# "ui.cursorline.primary" = { bg = "background_dark" }
"ui.help" = { fg = "base06", bg = "base01" }
# "ui.debug" = { fg = "red" }
# "ui.highlight.frameline" = { fg = "black", bg = "red" }
"ui.linenr" = { fg = "base03" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"]}
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { fg = "base01" }
"ui.selection" = { bg = "base02" }
# "ui.selection.primary" = { bg = "primary_highlight" }
"ui.statusline" = { fg = "base04", bg = "base01" }
# "ui.statusline.inactive" = { fg = "comment", bg = "background_dark" }
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = { fg = "base05" }
"ui.text.focus" = { fg = "base05" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = { fg = "base03" }
# "ui.virtual.wrap" = { fg = "subtle" }
"ui.window" = { fg = "base01" }

"error" = { fg = "base08" }
"warning" = { fg = "base09" }

"markup.heading" = { fg = "base0D", modifiers = ["bold"] }
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = { fg = "base0C", modifiers = ["italic"] }
"markup.raw" = { fg = "base0B" }

# "diagnostic".underline = { color = "orange", style = "curl" }
# "diagnostic.error".underline = { color = "red", style = "curl" }

[palette]
base00 = "#282936" # Default Background
base01 = "#3a3c4e" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#4d4f68" # Selection Background
base03 = "#626483" # Comments, Invisibles, Line Highlighting
base04 = "#62d6e8" # Dark Foreground (Used for status bars)
base05 = "#e9e9f4" # Default Foreground, Caret, Delimiters, Operators
base06 = "#f1f2f8" # Light Foreground (Not often used)
base07 = "#f7f7fb" # Light Background (Not often used)
base08 = "#ea51b2" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#b45bcf" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#00f769" # Classes, Markup Bold, Search Text Background
base0B = "#ebff87" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#a1efe4" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#62d6e8" # Functions, Methods, Attribute IDs, Headings
base0E = "#b45bcf" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#00f769" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
